# Generated by Django 4.0.1 on 2022-01-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerUser', '0002_registerusermodel_created_registerusermodel_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerusertwo',
            name='registerUserModel',
        ),
        migrations.DeleteModel(
            name='registerUserModel',
        ),
        migrations.DeleteModel(
            name='registerUserTwo',
        ),
    ]
