# Generated by Django 4.0.1 on 2022-03-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url_img',
            field=models.ImageField(blank=True, default='assets/img/default.png', null=True, upload_to='img/'),
        ),
    ]
