# Generated by Django 4.0.1 on 2022-01-27 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0002_alter_primertabla_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primertabla',
            old_name='edit',
            new_name='edited',
        ),
    ]
