# Generated by Django 4.0.1 on 2022-01-27 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0003_rename_edit_primertabla_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primertabla',
            old_name='name',
            new_name='nombre',
        ),
    ]
